{% set version = '1.2.2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-stabm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/stabm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stabm/stabm_{{ version }}.tar.gz
  sha256: 18ee4877d9197e642e78b6098d39e1c449d93456f0d1a9b386fcfe2b708b54ef

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix >=1.5_0
    - r-checkmate >=1.8.5
  run:
    - r-base
    - r-matrix >=1.5_0
    - r-checkmate >=1.8.5

test:
  commands:
    - $R -e "library('stabm')"           # [not win]
    - "\"%R%\" -e \"library('stabm')\""  # [win]

about:
  home: https://bommert.github.io/stabm/, https://github.com/bommert/stabm
  license: LGPL-3.0-only
  summary: An implementation of many measures for the assessment of the stability of feature
    selection. Both simple measures and measures which take into account the similarities
    between features are available, see Bommert (2020) <doi:10.17877/DE290R-21906>.
  license_family: LGPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
